<<<<<<< HEAD
-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 12:17:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaarias` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaarias` DEFAULT CHARACTER SET utf8 ;
USE `vaarias` ;

-- -----------------------------------------------------
-- Table `vaarias`.`tb_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_library` (
  `id` INT NOT NULL,
  `book_id` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `book_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_history` (
  `id` INT NOT NULL,
  `book_name` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NULL,
  `credit_card_number` VARCHAR(45) NULL,
  `client_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `passowrd` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tb_library_id` INT NOT NULL,
  `tb_history_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_library_id`, `tb_history_id`),
  INDEX `fk_tb_user_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  INDEX `fk_tb_user_tb_history1_idx` (`tb_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_tb_history1`
    FOREIGN KEY (`tb_history_id`)
    REFERENCES `vaarias`.`tb_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_credit_card` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `verification_code` INT NULL,
  `tb_user_id` INT NOT NULL,
  `client_name` VARCHAR(45) NULL,
  `client_cpf` VARCHAR(45) NULL,
  `tb_history_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_history_id`),
  INDEX `fk_tb_credit_card_tb_user_idx` (`tb_user_id` ASC) VISIBLE,
  INDEX `fk_tb_credit_card_tb_history1_idx` (`tb_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_credit_card_tb_user`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `vaarias`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_credit_card_tb_history1`
    FOREIGN KEY (`tb_history_id`)
    REFERENCES `vaarias`.`tb_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `cover_url` VARCHAR(100) NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_book_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_book_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vaarias` ;

-- -----------------------------------------------------
-- Table `vaarias`.`tb_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_library` (
  `id` INT NOT NULL,
  `book_id` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` VARCHAR(45) NULL DEFAULT NULL,
  `book_path` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `passowrd` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_library_id`),
  INDEX `fk_tb_user_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_credit_card` (
  `id` INT NOT NULL,
  `number` INT NULL DEFAULT NULL,
  `verification_code` INT NULL DEFAULT NULL,
  `tb_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_credit_card_tb_user_idx` (`tb_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_credit_card_tb_user`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `vaarias`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `cover_url` VARCHAR(100) NULL DEFAULT NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_book_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_book_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 12:17:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaarias` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vaarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaarias` DEFAULT CHARACTER SET utf8 ;
USE `vaarias` ;

-- -----------------------------------------------------
-- Table `vaarias`.`tb_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_library` (
  `id` INT NOT NULL,
  `book_id` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `book_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_history` (
  `id` INT NOT NULL,
  `book_name` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NULL,
  `credit_card_number` VARCHAR(45) NULL,
  `client_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `passowrd` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tb_library_id` INT NOT NULL,
  `tb_history_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_library_id`, `tb_history_id`),
  INDEX `fk_tb_user_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  INDEX `fk_tb_user_tb_history1_idx` (`tb_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_tb_history1`
    FOREIGN KEY (`tb_history_id`)
    REFERENCES `vaarias`.`tb_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_credit_card` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `verification_code` INT NULL,
  `tb_user_id` INT NOT NULL,
  `client_name` VARCHAR(45) NULL,
  `client_cpf` VARCHAR(45) NULL,
  `tb_history_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_history_id`),
  INDEX `fk_tb_credit_card_tb_user_idx` (`tb_user_id` ASC) VISIBLE,
  INDEX `fk_tb_credit_card_tb_history1_idx` (`tb_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_credit_card_tb_user`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `vaarias`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_credit_card_tb_history1`
    FOREIGN KEY (`tb_history_id`)
    REFERENCES `vaarias`.`tb_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `cover_url` VARCHAR(100) NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_book_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_book_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vaarias` ;

-- -----------------------------------------------------
-- Table `vaarias`.`tb_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_library` (
  `id` INT NOT NULL,
  `book_id` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` VARCHAR(45) NULL DEFAULT NULL,
  `book_path` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `passowrd` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_library_id`),
  INDEX `fk_tb_user_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_credit_card` (
  `id` INT NOT NULL,
  `number` INT NULL DEFAULT NULL,
  `verification_code` INT NULL DEFAULT NULL,
  `tb_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_credit_card_tb_user_idx` (`tb_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_credit_card_tb_user`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `vaarias`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaarias`.`tb_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaarias`.`tb_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `cover_url` VARCHAR(100) NULL DEFAULT NULL,
  `tb_library_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_book_tb_library1_idx` (`tb_library_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_book_tb_library1`
    FOREIGN KEY (`tb_library_id`)
    REFERENCES `vaarias`.`tb_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
>>>>>>> 44d8c04f4c493ac296c9aaa21285b63e1f048fc2
